### ISSUE TITLE
Ask for Ontologies

### ISSUE THREAD

**Issue by 2753664896** [GeoscienceAustralia/FSDF-Power-Stations#1]
Dear authors:
Could you expose the Powerlines, Power-Stations, and Power-Substations ontologies? I want to try to apply them in my paper. Thank you very much.

**Comment by ibastrak** [comment]
Hello 2753664896,

I wonder if you could let us know who you are and what your paper is about.
The ontologies are in preparation at the moment but should be available in February.
Regards
Irina
